server.port=8080

# MySQL — change password to yours
spring.datasource.url=jdbc:mysql://root:IIlzoxMmKChaXTPqeHpyzucdRDLxWFQA@maglev.proxy.rlwy.net:41523/railway?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=IIlzoxMmKChaXTPqeHpyzucdRDLxWFQA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT
app.jwt.secret=ContractLedger2024VeryLongSecretKeyForJWTSigning@Pungunuru
app.jwt.expiration=604800000

# CORS — add your frontend URL
app.cors.origins=http://localhost:8080,http://localhost:3000,https://YOUR-NETLIFY-APP.netlify.app

# Admin secret — required to register admin users
app.admin.secret=Admin@2024
